### ISSUE TITLE
author initials inconsistency

### ISSUE THREAD

**Issue by mverleg** [moutonf/academicResearcherCV#1]
I really like this template, good job on that. There's one problem for me though, I'm not sure if that's intentional (I'm not aware of this convention). The first author has initials after the name, but all others have initials before.

**Comment by moutonf** [comment]
I am really glad other people are also using the template and found it useful. I have gone through the code now and realised that it is in that format because of the style: authoryear which is used. In this style the first author has their surname first and then initials and all other authors are the other way around.

I have tried to change the style to numeric and ieee, however, that causes additional problems as the numbering is then forced which breaks the template. I will update the current template in due time, however, for now an ugly hack which you can use is the following:

%-------------------Including Biblatex package-------------------------------------------------------------

\usepackage[url=false,
    backend=biber,                                  % This can be set to either biber or bibtex. If references are missing just change back and forth between biber and bibtex..
    style=authoryear,
    doi=false,  
    isbn=false,
    backref=false,
    dashed=false,                                   % Do not add a dash out authors for subsequent articles with the same authors.
    maxnames=99,                                    % Amount of authors to include before abbreviating.
    sorting=ydnt]{biblatex}                         % Sorting in reverse order

In the above section, you should change the style section. Change it to the following and it should give the correct order of initial, surname:

%-------------------Including Biblatex package-------------------------------------------------------------

\usepackage[url=false,
    backend=biber,                                  % This can be set to either biber or bibtex. If references are missing just change back and forth between biber and bibtex..
    style=standard,
    doi=false,  
    isbn=false,
    backref=false,
    dashed=false,                                   % Do not add a dash out authors for subsequent articles with the same authors.
    maxnames=99,                                    % Amount of authors to include before abbreviating.
    sorting=ydnt]{biblatex}                         % Sorting in reverse order

Please take note, it does give compilation errors then, but as far as I can see it does not have any impact on the referencing section.

I will try to update a style sheet for the IEEE format within July. Thank you for bringing up this issue.

**Comment by mverleg** [comment]
Yeah I also noticed that changing the style doesn't work. Thanks for the workaround, I'll try!
